SELECT
  applicants.uuid,
  applicants.id,
  countries.rdbms_id,
  applicants.referrer_lg_rider_uuid,
  applicants.referrer_lg_rider_id,
  applicants.lg_city_uuid,
  applicants.lg_city_id,
  applicants.lg_language_id,
  applicants.lg_rider_uuid,
  applicants.lg_rider_id,
  applicants.url_id,

  applicants.region,
  applicants.country_code,

  applicants.is_duplicate,
  applicants.is_braze_welcome_sent,
  applicants.rejection_category_type,
  applicants.rejection_type,
  applicants.link_type,
  applicants.url,
  applicants.link_click_count,
  applicants.timezone,
  applicants.created_date_utc,
  applicants.created_at_local,
  applicants.created_at_utc,
  applicants.braze_user_created_at_local,
  applicants.braze_user_created_at_utc,
  applicants.last_reminded_at_local,
  applicants.last_reminded_at_utc,
  applicants.rejected_at_local,
  applicants.rejected_at_utc,
  applicants.approved_at_local,
  applicants.approved_at_utc,
  applicants.custom_fields,
  applicants.workflow,
FROM `{project_id}.pandata_intermediate.lg_applicants` AS applicants
LEFT JOIN `{project_id}.pandata_intermediate.pd_countries` AS countries
       ON applicants.country_code = countries.lg_country_code
