SELECT
  issues.id,
  issues.uuid,
  countries.rdbms_id,
  issues.lg_delivery_id,
  issues.lg_delivery_uuid,
  issues.lg_rider_id,
  issues.lg_rider_uuid,
  issues.lg_city_id,
  issues.lg_city_uuid,
  issues.lg_zone_id,
  issues.lg_zone_uuid,
  issues.country_code,
  issues.name,
  issues.notes,
  issues.is_shown_on_watchlist,
  issues.type,
  issues.category,
  issues.timezone,
  issues.picked_at_utc,
  issues.picked_by_utc,
  issues.dismissed_at_utc,
  issues.resolved_at_utc,
  issues.created_date_utc,
  issues.created_at_utc,
  issues.updated_at_utc,
  issues.actions,
FROM `{project_id}.pandata_intermediate.lg_issues` AS issues
LEFT JOIN `{project_id}.pandata_intermediate.pd_countries` AS countries
       ON issues.country_code = countries.lg_country_code
