# gcloud builds submit . --config=cloudbuild.yaml
---
steps:
  - name: 'gcr.io/${PROJECT_ID}/pylint'
    args: [ 'pro/airflow/dags/', "--ignore-patterns=pro/airflow/dags/__init__.py"]
tags: ['test-pylint-cb']