# BUILD AIRFLOW WITH PYLINT
steps:
# Creating PR and github workflow
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=ci_GITHUB --format='get(payload.data)' | tr '_-' '/+' | base64 -d > CICD_GITHUB.txt" ]
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: Build Github Container
  args: ['build', '-t', 'us.gcr.io/${PROJECT_ID}/peya-data-ops-github-ci:${SHORT_SHA}', 'ci/github_cli']
  timeout: 500s
  # Tag Image
- name: 'gcr.io/cloud-builders/docker'
  id: Github Image Tagged with latest
  args: ['tag', 'us.gcr.io/${PROJECT_ID}/peya-data-ops-github-ci:${SHORT_SHA}' , 'us.gcr.io/${PROJECT_ID}/peya-data-ops-github-ci:latest']  
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push Github Container
  args: ['push', 'us.gcr.io/${PROJECT_ID}/peya-data-ops-github-ci:${SHORT_SHA}']
# images:
# - 'us.gcr.io/$PROJECT_ID/peya-data-ops-airflow-ci:$SHORT_SHA'
# - 'us.gcr.io/$PROJECT_ID/peya-data-ops-airflow-ci:latest'

# RUN AIRLFOW TEST
# steps:
# - name: 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}'
#   id: 'test-pylint-cb'
#   args: [ 'pylint', 'pro/airflow/dags/']
# run the dag tests
# - name: 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}'
#   id: 'test-dags'
#   args: ["pytest", "-s", "/dags/dag_validation.py"]
# GITHUB AUTH LOGIN
- name: 'us.gcr.io/${PROJECT_ID}/peya-data-ops-github-ci:${SHORT_SHA}'
  # entrypoint: 'bash'
  id: 'gh-auth'
  args: ["auth login --with-token < CICD_GITHUB.txt"]
# TEST GH
- name: 'us.gcr.io/${PROJECT_ID}/peya-data-ops-github-ci:${SHORT_SHA}'
  id: 'gh-test'
  args: ['repo', 'view', 'pedidosya/data-ops-tf-iac']
images:
- 'us.gcr.io/$PROJECT_ID/peya-data-ops-github-ci:$SHORT_SHA'
- 'us.gcr.io/$PROJECT_ID/peya-data-ops-github-ci:latest'


# # BUILD AIRFLOW WITH PYLINT
# steps:
# # Creating PR and github workflow
# - name: gcr.io/cloud-builders/gcloud
#   entrypoint: 'bash'
#   args: [ '-c', "gcloud secrets versions access latest --secret=ci_GITHUB --format='get(payload.data)' | tr '_-' '/+' | base64 -d > ci/ci_GITHUB.txt" ]
#   # build the container image
# - name: 'gcr.io/cloud-builders/docker'
#   id: Build Airflow Container
#   args: ['build', '-t', 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}', 'ci/']
#   timeout: 500s
#   # Tag Image
# - name: 'gcr.io/cloud-builders/docker'
#   id: Airflow Image Tagged with latest
#   args: ['tag', 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}' , 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:latest']  
#   # push the container image to Container Registry
# - name: 'gcr.io/cloud-builders/docker'
#   id: Push Airflow Container
#   args: ['push', 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}']
# # images:
# # - 'us.gcr.io/$PROJECT_ID/peya-data-ops-airflow-ci:$SHORT_SHA'
# # - 'us.gcr.io/$PROJECT_ID/peya-data-ops-airflow-ci:latest'

# # RUN AIRLFOW TEST
# # steps:
# # - name: 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}'
# #   id: 'test-pylint-cb'
# #   args: [ 'pylint', 'pro/airflow/dags/']
# # run the dag tests
# # - name: 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}'
# #   id: 'test-dags'
# #   args: ["pytest", "-s", "/dags/dag_validation.py"]
# # GITHUB AUTH LOGIN
# - name: 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}'
#   # entrypoint: 'bash'
#   id: 'gh-auth'
#   args: ["gh auth login --with-token < /dags/ci_GITHUB.txt"]
# # TEST GH
# - name: 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}'
#   id: 'gh-test'
#   args: ['gh', 'repo', 'view', 'pedidosya/data-ops-tf-iac']
# images:
# - 'us.gcr.io/$PROJECT_ID/peya-data-ops-airflow-ci:$SHORT_SHA'
# - 'us.gcr.io/$PROJECT_ID/peya-data-ops-airflow-ci:latest'