# gcloud builds submit . --config=cloudbuild.yaml
---
steps:
  # build the docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker build'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/peya-data-ops-airflow-cicd:${SHORT_SHA}', 'ci/'] # tag docker image with commit sha
  # push to registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push container
    args: ['push', 'us.gcr.io/$PROJECT_ID/peya-data-ops-airflow-cicd:${SHORT_SHA}']
  # run pylint tests
  - name: 'gcr.io/${PROJECT_ID}/peya-data-ops-airflow-cicd:${SHORT_SHA}'
    id: 'test-pylint-cb'
    args: [ 'pro/airflow/dags/']
  # run the dag tests
  - name: 'gcr.io/cloud-builders/docker'
    id: 'test-dags'
    args: ['run', 'gcr.io/${PROJECT_ID}/peya-data-ops-airflow-cicd:${SHORT_SHA}']