# gcloud builds submit . --config=cloudbuild.yaml
---
steps:
  - name: 'gcr.io/${PROJECT_ID}/pylint'
    args: ["-c", 'pro/airflow/dags/*.py', "--ignore-patters='*/__init__.py'"]
tags: ['test-pylint-cb']