# BUILD AIRFLOW WITH PYLINT
steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: Build Airflow Container
  args: ['build', '-t', 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}', 'ci/']
  timeout: 500s
  # Tag Image
- name: 'gcr.io/cloud-builders/docker'
  id: Airflow Image Tagged with latest
  args: ['tag', 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}' , 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:latest']  
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push Airflow Container
  args: ['push', 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}']
  # RUN AIRLFOW TEST
- name: 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}'
  id: 'test-pylint-cb'
  args: [ 'pylint', 'pro/airflow/dags/']
  # run the dag tests
- name: 'us.gcr.io/${PROJECT_ID}/peya-data-ops-airflow-ci:${SHORT_SHA}'
  id: 'test-dags'
  args: ["pytest", "-s", "/dags/dag_validation.py"]
images:
# - 'us.gcr.io/$PROJECT_ID/peya-data-ops-airflow-ci:$SHORT_SHA'
- 'us.gcr.io/$PROJECT_ID/peya-data-ops-airflow-ci:latest'