# gcloud builds submit . --config=cloudbuild.yaml
---
steps:
  # - name: 'gcr.io/${PROJECT_ID}/pylint'
  #   id: 'test-pylint-cb'
  #   args: [ 'pro/airflow/dags/']

  # build the docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker build'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/peya-data-ops-airflow-cicd:${SHORT_SHA}', 'airflow_test/'] # tag docker image with commit sha
  - name: 'gcr.io/cloud-builders/docker'
    id: Push container
    args: ['push', 'us.gcr.io/$PROJECT_ID/peya-data-ops-airflow-cicd:${SHORT_SHA}']
  # run the dag tests
  - name: 'gcr.io/cloud-builders/docker'
    id: 'test-dags'
    args: ['run', 'gcr.io/${PROJECT_ID}/peya-data-ops-airflow-cicd:${SHORT_SHA}']