version: '3.5'

networks:
  dwh:
    name: dwh

services:
  webserver:
    build: .
    image: datahub-airflow
    container_name: airflow-webserver
    hostname: webserver
    command: webserver
    volumes:
      - ./docker/airflow/config:/opt/airflow/config:cached
      - ./docker/airflow/airflow.cfg:/opt/airflow/airflow.cfg:cached
      - ./docker/airflow/webserver_config.py:/opt/airflow/webserver_config.py:cached
      - ./docker/rootdir/entrypoint:/entrypoint:cached
      - ./bin:/opt/airflow/bin:cached
      - ./dags:/opt/airflow/dags:cached
      - ./src:/opt/airflow/src:cached
      - ./tests:/opt/airflow/tests:cached
      - ./logs:/opt/airflow/logs:cached
      - ./.flake8:/opt/airflow/.flake8:cached
      - ~/.aws:/home/airflow/.aws:cached
      - ~/.config:/home/airflow/.config:cached
      - ~/.kube_tool:/home/airflow/.kube_tool:cached
      - ./.yamllint.yml:/opt/airflow/.yamllint.yml:cached
    env_file:
      - .env
    environment:
      AIRFLOW_CONN_DATABRICKS_DEFAULT: databricks://dbc-d78d06da-7f8d.cloud.databricks.com?token=${DATABRICKS_TOKEN:-}
      AIRFLOW__KUBERNETES__DAGS_VOLUME_HOST: ${AIRFLOW_PATH:-./}/dags
      AIRFLOW__KUBERNETES__LOGS_VOLUME_HOST: ${AIRFLOW_PATH:-./}/logs
      AIRFLOW_BUSINESS_UNIT: ${AIRFLOW_BUSINESS_UNIT}
      AIRFLOW__WEBSERVER__UPDATE_FAB_PERMS: ${AIRFLOW__WEBSERVER__UPDATE_FAB_PERMS:-False}
      JDBC_LOG_PASSWORD: ${JDBC_LOG_PASSWORD:-}
      PYTHONPATH: /opt/airflow/src
    ports:
      - "8080:8080"
    networks:
      - dwh
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 10s
      retries: 3
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
      - net.ipv4.tcp_keepalive_intvl=200
      - net.ipv4.tcp_keepalive_probes=5

  mysql:
    image: mysql:5.7
    container_name: airflow-mysql
    hostname: mysql
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql:consistent
      - ./docker/mysql/etc/mysql/conf.d/airflow.cnf:/etc/mysql/conf.d/airflow.cnf:cached
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:cached
    environment:
      MYSQL_ROOT_PASSWORD: airflow
    networks:
      - dwh
    ports:
      - "3306:3306"
