schedule_group_1 = "30 10 * * *"
schedule_group_2 = "0 11 * * *"
schedule_group_3 = "45 10 * * *"

monthly_schedule = "0 11 1 * *"

# S3
dmarts_s3_bucket = "peya.dh.dmarts"
dmarts_source_dir = "central-dwh/dwh_il_darkstore"
pandora_target_dir = "refined/pandora"
dmarts_gcs_bucket = "data-origins-storage"
dmarts_gcs_target_dir = "dmarts"

dag_bag = {
    'dmarts': {
        "scheduler": schedule_group_1,
        "name": "dmarts",
        "active": True,
        "retries": 5,
        "catchup": False,
        "start_year": 2019,
        "start_month": 9,
        "start_day": 1,
        'tables': {
            'purchase_orders': {
                "testing": False,
                "name": "purchase-orders",
                "active": True,
                "date_str": '{{ ds }}',
                "date_id": '{{ execution_date.strftime("%Y%m") }}',
                "model": "purchase_orders",
                "has_dwh_table": True,
                "send_slack": True,
                "date_filter": True,
                "filter_column": "created_date_ts",
                "spark_script": "spark_script.py",
                'update_type': 'FULL',
                'update_prev': True,
                "days_back": 2,
                "country_col": None,
                "date_id_col": None,
                "types_conversion": None,
                # "partitioning": {
                #     "col_name": "CreatedDate",
                #     "CreatedDate": {
                #         "type": "timestamp",
                #         "level": "day",
                #     }
                # },
                "source_bucket": dmarts_s3_bucket,
                "source_dir": dmarts_source_dir,
                "source_folder": "fct_purchase_orders",
                "target_dir": dmarts_gcs_target_dir,
                "target_folder": "fct_purchase_orders",
            },
            'purchase_order_lines': {
                "testing": False,
                "name": "purchase-order-lines",
                "active": True,
                "scheduler": schedule_group_1,
                "retries": 5,
                "catchup": False,
                "start_year": 2019,
                "start_month": 9,
                "start_day": 1,
                "date_str": '{{ ds }}',
                "date_id": '{{ execution_date.strftime("%Y%m") }}',
                "model": "purchase_order_lines",
                "has_dwh_table": True,
                "send_slack": True,
                "date_filter": True,
                "filter_column": "created_date_ts",
                "spark_script": "spark_script.py",
                'update_type': 'FULL',
                'update_prev': True,
                "days_back": 2,
                "country_col": None,
                "date_id_col": None,
                "types_conversion": None,
                # "partitioning": {
                #     "col_name": "CreatedDate",
                #     "CreatedDate": {
                #         "type": "timestamp",
                #         "level": "day",
                #     }
                # },
                "source_bucket": dmarts_s3_bucket,
                "source_dir": dmarts_source_dir,
                "source_folder": "fct_purchase_order_lines",
                "target_dir": dmarts_gcs_target_dir,
                "target_folder": "fct_purchase_order_lines",
            },
            'customer_orders': {
                "testing": False,
                "name": "customer-orders",
                "active": True,
                "scheduler": schedule_group_1,
                "retries": 5,
                "catchup": False,
                "start_year": 2019,
                "start_month": 9,
                "start_day": 1,
                "date_str": '{{ ds }}',
                "date_id": '{{ execution_date.strftime("%Y%m") }}',
                "model": "customer_orders",
                "has_dwh_table": True,
                "send_slack": True,
                "date_filter": True,
                "filter_column": "date",
                "spark_script": "spark_script.py",
                'update_type': 'FULL',
                'update_prev': True,
                "days_back": 2,
                "country_col": None,
                "date_id_col": None,
                "types_conversion": None,
                # "partitioning": {
                #     "col_name": "CreatedDate",
                #     "CreatedDate": {
                #         "type": "timestamp",
                #         "level": "day",
                #     }
                # },
                "source_bucket": dmarts_s3_bucket,
                "source_dir": dmarts_source_dir,
                "source_folder": "fct_customer_orders",
                "target_dir": dmarts_gcs_target_dir,
                "target_folder": "fct_customer_orders",
            },
            'customer_order_lines': {
                "testing": False,
                "name": "customer-orders-lines",
                "active": True,
                "scheduler": schedule_group_1,
                "retries": 5,
                "catchup": False,
                "start_year": 2019,
                "start_month": 9,
                "start_day": 1,
                "date_str": '{{ ds }}',
                "date_id": '{{ execution_date.strftime("%Y%m") }}',
                "model": "customer_order_lines",
                "has_dwh_table": True,
                "send_slack": True,
                "date_filter": True,
                "filter_column": "date",
                "spark_script": "spark_script.py",
                'update_type': 'FULL',
                'update_prev': True,
                "days_back": 2,
                "country_col": None,
                "date_id_col": None,
                "types_conversion": None,
                # "partitioning": {
                #     "col_name": "CreatedDate",
                #     "CreatedDate": {
                #         "type": "timestamp",
                #         "level": "day",
                #     }
                # },
                "source_bucket": dmarts_s3_bucket,
                "source_dir": dmarts_source_dir,
                "source_folder": "fct_customer_order_lines",
                "target_dir": dmarts_gcs_target_dir,
                "target_folder": "fct_customer_order_lines",
            },
            'purchase_order_status': {
                "testing": False,
                "name": "purchase-order-status",
                "active": True,
                "scheduler": schedule_group_1,
                "retries": 5,
                "catchup": False,
                "start_year": 2019,
                "start_month": 9,
                "start_day": 1,
                "date_str": '{{ ds }}',
                "date_id": '{{ execution_date.strftime("%Y%m") }}',
                "model": "purchase_order_status",
                "has_dwh_table": True,
                "send_slack": True,
                "date_filter": True,
                "filter_column": None,
                "spark_script": "spark_script.py",
                'update_type': 'FULL',
                'update_prev': True,
                "days_back": 2,
                "country_col": None,
                "date_id_col": None,
                "types_conversion": None,
                # "partitioning": {
                #     "col_name": "CreatedDate",
                #     "CreatedDate": {
                #         "type": "timestamp",
                #         "level": "day",
                #     }
                # },
                "source_bucket": dmarts_s3_bucket,
                "source_dir": dmarts_source_dir,
                "source_folder": "dim_purchase_order_status",
                "target_dir": dmarts_gcs_target_dir,
                "target_folder": "dim_purchase_order_status",
            },
            'picker_shifts': {
                "testing": False,
                "name": "picker-shifts",
                "active": True,
                "scheduler": schedule_group_1,
                "retries": 5,
                "catchup": False,
                "start_year": 2019,
                "start_month": 9,
                "start_day": 1,
                "date_str": '{{ ds }}',
                "date_id": '{{ execution_date.strftime("%Y%m") }}',
                "model": "picker_shifts",
                "has_dwh_table": True,
                "send_slack": True,
                "date_filter": True,
                "filter_column": "shift_start_at",
                "spark_script": "spark_script.py",
                'update_type': 'FULL',
                'update_prev': True,
                "days_back": 2,
                "country_col": None,
                "date_id_col": None,
                "types_conversion": None,
                # "partitioning": {
                #     "col_name": "CreatedDate",
                #     "CreatedDate": {
                #         "type": "timestamp",
                #         "level": "day",
                #     }
                # },
                "source_bucket": dmarts_s3_bucket,
                "source_dir": dmarts_source_dir,
                "source_folder": "fct_picker_shifts",
                "target_dir": dmarts_gcs_target_dir,
                "target_folder": "fct_picker_shifts",
            },
            'picker_shifts_performance': {
                "testing": False,
                "name": "picker-shifts-performance",
                "active": True,
                "scheduler": schedule_group_1,
                "retries": 5,
                "catchup": False,
                "start_year": 2019,
                "start_month": 9,
                "start_day": 1,
                "date_str": '{{ ds }}',
                "date_id": '{{ execution_date.strftime("%Y%m") }}',
                "model": "picker_shifts_performance",
                "has_dwh_table": True,
                "send_slack": True,
                "date_filter": True,
                "filter_column": "shift_date",
                "spark_script": "spark_script.py",
                'update_type': 'FULL',
                'update_prev': True,
                "days_back": 2,
                "country_col": None,
                "date_id_col": None,
                "types_conversion": None,
                # "partitioning": {
                #     "col_name": "CreatedDate",
                #     "CreatedDate": {
                #         "type": "timestamp",
                #         "level": "day",
                #     }
                # },
                "source_bucket": dmarts_s3_bucket,
                "source_dir": dmarts_source_dir,
                "source_folder": "fct_picker_shifts_performance",
                "target_dir": dmarts_gcs_target_dir,
                "target_folder": "fct_picker_shifts_performance",
            },
            'picker_performance': {
                "testing": False,
                "name": "picker-performance",
                "active": True,
                "scheduler": schedule_group_1,
                "retries": 5,
                "catchup": False,
                "start_year": 2019,
                "start_month": 9,
                "start_day": 1,
                "date_str": '{{ ds }}',
                "date_id": '{{ execution_date.strftime("%Y%m") }}',
                "model": "picker_performance",
                "has_dwh_table": True,
                "send_slack": True,
                "date_filter": True,
                "filter_column": "order_date",
                "spark_script": "spark_script.py",
                'update_type': 'FULL',
                'update_prev': True,
                "days_back": 2,
                "country_col": None,
                "date_id_col": None,
                "types_conversion": None,
                # "partitioning": {
                #     "col_name": "CreatedDate",
                #     "CreatedDate": {
                #         "type": "timestamp",
                #         "level": "day",
                #     }
                # },
                "source_bucket": dmarts_s3_bucket,
                "source_dir": dmarts_source_dir,
                "source_folder": "fct_picker_performance",
                "target_dir": dmarts_gcs_target_dir,
                "target_folder": "fct_picker_performance",
            },
            'picker_order_events': {
                "testing": False,
                "name": "picker-order-events",
                "active": True,
                "scheduler": schedule_group_1,
                "retries": 5,
                "catchup": False,
                "start_year": 2019,
                "start_month": 9,
                "start_day": 1,
                "date_str": '{{ ds }}',
                "date_id": '{{ execution_date.strftime("%Y%m") }}',
                "model": "picker_order_events",
                "has_dwh_table": True,
                "send_slack": True,
                "date_filter": True,
                "filter_column": "created_at_ts",
                "spark_script": "spark_script.py",
                'update_type': 'FULL',
                'update_prev': True,
                "days_back": 2,
                "country_col": None,
                "date_id_col": None,
                "types_conversion": None,
                # "partitioning": {
                #     "col_name": "CreatedDate",
                #     "CreatedDate": {
                #         "type": "timestamp",
                #         "level": "day",
                #     }
                # },
                "source_bucket": dmarts_s3_bucket,
                "source_dir": dmarts_source_dir,
                "source_folder": "fct_picker_order_events",
                "target_dir": dmarts_gcs_target_dir,
                "target_folder": "fct_picker_order_events",
            },
            'product': {
                "testing": False,
                "name": "product",
                "active": True,
                "scheduler": schedule_group_1,
                "retries": 5,
                "catchup": False,
                "start_year": 2019,
                "start_month": 9,
                "start_day": 1,
                "date_str": '{{ ds }}',
                "date_id": '{{ execution_date.strftime("%Y%m") }}',
                "model": "product",
                "has_dwh_table": True,
                "send_slack": True,
                "date_filter": True,
                "filter_column": None,
                "spark_script": "spark_script.py",
                'update_type': 'FULL',
                'update_prev': True,
                "days_back": 2,
                "country_col": None,
                "date_id_col": None,
                "types_conversion": None,
                # "partitioning": {
                #     "col_name": "CreatedDate",
                #     "CreatedDate": {
                #         "type": "timestamp",
                #         "level": "day",
                #     }
                # },
                "source_bucket": dmarts_s3_bucket,
                "source_dir": dmarts_source_dir,
                "source_folder": "dim_product",
                "target_dir": dmarts_gcs_target_dir,
                "target_folder": "dim_product",
            },
            'warehouse': {
                "testing": False,
                "name": "warehouse",
                "active": True,
                "scheduler": schedule_group_1,
                "retries": 5,
                "catchup": False,
                "start_year": 2019,
                "start_month": 9,
                "start_day": 1,
                "date_str": '{{ ds }}',
                "date_id": '{{ execution_date.strftime("%Y%m") }}',
                "model": "warehouse",
                "has_dwh_table": True,
                "send_slack": True,
                "date_filter": True,
                "filter_column": None,
                "spark_script": "spark_script.py",
                'update_type': 'FULL',
                'update_prev': True,
                "days_back": 2,
                "country_col": None,
                "date_id_col": None,
                "types_conversion": None,
                # "partitioning": {
                #     "col_name": "CreatedDate",
                #     "CreatedDate": {
                #         "type": "timestamp",
                #         "level": "day",
                #     }
                # },
                "source_bucket": dmarts_s3_bucket,
                "source_dir": dmarts_source_dir,
                "source_folder": "dim_warehouse",
                "target_dir": dmarts_gcs_target_dir,
                "target_folder": "dim_warehouse",
            },
            'supplier': {
                "testing": False,
                "name": "supplier",
                "active": True,
                "scheduler": schedule_group_1,
                "retries": 5,
                "catchup": False,
                "start_year": 2019,
                "start_month": 9,
                "start_day": 1,
                "date_str": '{{ ds }}',
                "date_id": '{{ execution_date.strftime("%Y%m") }}',
                "model": "supplier",
                "has_dwh_table": True,
                "send_slack": True,
                "date_filter": True,
                "filter_column": None,
                "spark_script": "spark_script.py",
                'update_type': 'FULL',
                'update_prev': True,
                "days_back": 2,
                "country_col": None,
                "date_id_col": None,
                "types_conversion": None,
                # "partitioning": {
                #     "col_name": "CreatedDate",
                #     "CreatedDate": {
                #         "type": "timestamp",
                #         "level": "day",
                #     }
                # },
                "source_bucket": dmarts_s3_bucket,
                "source_dir": dmarts_source_dir,
                "source_folder": "dim_supplier",
                "target_dir": dmarts_gcs_target_dir,
                "target_folder": "dim_supplier",
            },
            'source': {
                "testing": False,
                "name": "source",
                "active": True,
                "scheduler": schedule_group_1,
                "retries": 5,
                "catchup": False,
                "start_year": 2019,
                "start_month": 9,
                "start_day": 1,
                "date_str": '{{ ds }}',
                "date_id": '{{ execution_date.strftime("%Y%m") }}',
                "model": "source",
                "has_dwh_table": True,
                "send_slack": True,
                "date_filter": True,
                "filter_column": None,
                "spark_script": "spark_script.py",
                'update_type': 'FULL',
                'update_prev': True,
                "days_back": 2,
                "country_col": None,
                "date_id_col": None,
                "types_conversion": None,
                # "partitioning": {
                #     "col_name": "CreatedDate",
                #     "CreatedDate": {
                #         "type": "timestamp",
                #         "level": "day",
                #     }
                # },
                "source_bucket": dmarts_s3_bucket,
                "source_dir": dmarts_source_dir,
                "source_folder": "dim_source",
                "target_dir": dmarts_gcs_target_dir,
                "target_folder": "dim_source",
            },
        }
    }
}
