slack:
  channel: '#dh-datahub-peya'
  channel_errors: '#dh-datahub-peya-alerts'

# TODO Please update the GCS bucket to use the one owned by the business unit
gcs_production: &gcs_production
  bucket_name: 'fulfilment-dwh-production-import'

bigquery:
  <<: *gcs_production
  project_id: 'fulfillment-dwh-production'
  create_views: true
