teams:
  data-engineering:
    members:
      - U99Q7QP7F # Islam Azab
      - U0147UV9J15 # Tomasz Sosinski
      - U016ZCT7M8S # Abhushan Sahu

slack:
  channel: ''
  channel_errors: ''
  has_mentions: false

business-unit:
  name: "dmart"

gcs_staging: &gcs_staging
  bucket_name: 'fulfilment-dwh-staging-import'

pools:
  export_cloud_sql:
    name: export_cloud_sql
    slots: 10
    description: "Pool for export_cloud_sql in import-dwh-* DAG operators"
  export_cloud_sql_backfill:
    name: export_cloud_sql_backfill
    slots: 10
    description: "Pool for export_cloud_sql_backfill in import-dwh-backfill-raw-layer DAG operators"

# DAG configurations
dags:
  curated-data:
    schedule_interval: '0 1,5,9,13,17,21 * * *'
  import-dwh:
    schedule_interval: '0 3,7,11,15,19,23 * * *'

# See BigQueryCheckMetadataExecutionOperator to why it is set to production
bigquery_check_metadata_execution:
  project_id: 'fulfillment-dwh-production'

bigquery:
  <<: *gcs_staging
  project_id: 'fulfillment-dwh-staging'
  staging_project_id: 'fulfillment-dwh-staging'
  dataset:
    staging: staging_dmart
    raw: raw_dmart
    dl: dl_dmart
    hl: hl_dmart
    cl: cl_dmart
    curated_data_filtered: curated_data_filtered_dmart
    curated_data_shared: curated_data_shared_dmart
    acl: acl_dmart

  create_views: false

raw_layer_backfill:
  countries: ~         # List of countries to filter the import.
                       # Empty array means all countries.
                       # Null value disable the import for not regional applications.
  regions: ~           # List of regions to filter the import.
                       # Empty array means all regions.
                       # Null value disable the import for regional applications.
  from_date: ~         # Datetime format: %Y-%m-%d %H:%M:%S
  to_date: ~           # Datetime format: %Y-%m-%d %H:%M:%S
