# Example
#opsgenie:
#  responders:
#    - name: 'Fulfillment-Data'
#      type: 'team'
#  visibleTo:
#    - name: 'Fulfillment-Data'
#      type: 'team'
# For more information: https://docs.opsgenie.com/docs/python-sdk-alert
#                       https://docs.opsgenie.com/docs/alert-api#section-create-alert
#                       https://docs.opsgenie.com/docs/python-sdk-alert#add-details-custom-properties-to-alert
#

bigquery:
  dataset:
    staging: ~
    raw: ~
    dl: ~
    hl: ~
    cl: ~
    acl: ~
    curated_data_filtered: ~
    curated_data_shared: ~
  bigquery_conn_id_flat: 'bigquery_default'
  bigquery_conn_id_on_demand: 'bigquery_default'

pools:
  export_read_replica:
    name: export_read_replica
    slots: 10
    description: "Pool for export_read_replica in import-dwh-read-replica DAG operators"
  export_read_replica_backfill:
    name: export_read_replica_backfill
    slots: 10
    description: "Pool for export_read_replica_backfill in import-dwh-backfill-raw-layer DAG operators"
  export_read_replica_misc:
    name: export_read_replica_misc
    slots: 100
    description: "Pool for miscellaneous tasks in import-dwh-read-replica DAG"
  curated_data_misc:
    name: curated_data_misc
    slots: 100
    description: "Pool for curated-data DAG used by any operators"
  curated_data_queries:
    name: curated_data_queries
    slots: 100
    description: "Pool for curated-data DAG used to run queries"
  curated_data_long_running_queries:
    name: curated_data_long_running_queries
    slots: 1
    description: "Pool for curated-data DAG used to run long running queries"
