teams: []

slack:
  channel: ''
  channel_errors: ''
  channel_cost_monitoring:
    name: ''
    id: ''
  has_mentions: false

#opsgenie:
#  responders:
#    - name: 'Fulfillment-Data'
#      type: 'team'
#  visibleTo:
#    - name: 'Fulfillment-Data'
#      type: 'team'
# For more information: https://docs.opsgenie.com/docs/python-sdk-alert
#                       https://docs.opsgenie.com/docs/alert-api#section-create-alert
#                       https://docs.opsgenie.com/docs/python-sdk-alert#add-details-custom-properties-to-alert
opsgenie: {}

# TODO Please replace the name `BUSINESS_UNIT` with your business_unit name.
business-unit:
  name: BUSINESS_UNIT

# DAG configurations
dags: {}

# TODO Please update the GCS bucket to use the one owned by the business unit
gcs_staging: &gcs_staging
  bucket_name: 'fulfilment-dwh-staging-import'

# See BigQueryCheckMetadataExecutionOperator to why it is set to production
bigquery_check_metadata_execution:
  project_id: 'fulfillment-dwh-production'

# TODO Please replace the suffix BUSINESS_UNIT with your business_unit name.
bigquery:
  <<: *gcs_staging
  project_id: 'fulfillment-dwh-staging'
  staging_project_id: 'fulfillment-dwh-staging'
  dataset:
    staging: staging_BUSINESS_UNIT
    raw: raw_BUSINESS_UNIT
    dl: dl_BUSINESS_UNIT
    hl: hl_BUSINESS_UNIT
    cl: cl_BUSINESS_UNIT
    acl: acl_BUSINESS_UNIT
    curated_data_filtered: curated_data_filtered_BUSINESS_UNIT
    curated_data_shared: curated_data_shared_BUSINESS_UNIT
  create_views: false
