slack:
  channel: '#dh-datahub-pandora'
  channel_errors: '#dh-datahub-pandora-alerts'

gcs_production: &gcs_production
  bucket_name: 'pd-bi-datahub'

bigquery:
  <<: *gcs_production
  project_id: 'fulfillment-dwh-production'
  create_views: true
