apiVersion: v1
kind: Service
metadata:
  labels:
    com.docker.service.id: airflow-webserver
    com.docker.service.name: webserver
    com.docker.stack.namespace: airflow
  name: webserver
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    protocol: TCP
    targetPort: 55555
  selector:
    com.docker.service.id: airflow-webserver
    com.docker.service.name: webserver
    com.docker.stack.namespace: airflow
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    com.docker.service.id: airflow-webserver
    com.docker.service.name: webserver
    com.docker.stack.namespace: airflow
  name: webserver-published
  namespace: default
spec:
  ports:
  - name: 8080-tcp
    nodePort: 30584
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    com.docker.service.id: airflow-webserver
    com.docker.service.name: webserver
    com.docker.stack.namespace: airflow
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  labels:
    com.docker.service.id: airflow-scheduler
    com.docker.service.name: scheduler
    com.docker.stack.namespace: airflow
  name: scheduler
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    protocol: TCP
    targetPort: 55555
  selector:
    com.docker.service.id: airflow-scheduler
    com.docker.service.name: scheduler
    com.docker.stack.namespace: airflow
  sessionAffinity: None
  type: ClusterIP
