INSERT INTO peyabi.public.dim_restaurant_data
      (restaurant_id
       , restaurant_name
       , restaurant_state_id
       , restaurant_type_id
       , area_id
       , city_id
       , country_id
       , registered_date_id
       , registered_date
       , backend_id
       , rut
       , commission
       , is_vip
       , is_gold_vip
       , is_important_account
       , has_online_payment
       , has_stamps
       , has_pos
       , is_talent
       , has_featured_product
       , has_discount
       , last_order_date
       , first_order_date
       , restaurant_street
       , restaurant_door_number
       , restaurant_phone
       , restaurant_owner_contact_name
       , restaurant_owner_contact_last_name
       , restaurant_owner_contact_phones
       , reception_system_name
       , delivery_time
       , min_shipping_amount
       , max_shipping_amount
       , min_delivery_amount
       , max_delivery_amount
       , qty_zones
       , publicity_cost
       , automation_cost
       , avg_rating
       , main_cousine
       , link
       , logo
       , is_debtor
       , contract_number
       , previous_state_id
       , change_state_date_id
       , avg_rating_speed
       , qty_current_gold_vip
       , qty_current_featured_product
       , is_logistic
       , account_owner
       , is_day
       , is_night
       , address_id
       , is_premium
       , disabled_reason
       , avg_total_amount_last_3_month
       , avg_qty_order_last_3_month
       , reception_system_enabled
       , has_mov
       , is_express
       , main_cousine_category_id
)
(
SELECT   restaurant_id
       , restaurant_name
       , restaurant_state_id
       , restaurant_type_id
       , area_id
       , CASE WHEN city_id IS NULL THEN 0 ELSE city_id END
       , country_id
       , registered_date_id
       , registered_date
       , backend_id
       , rut
       , commission
       , is_vip
       , is_gold_vip
       , is_important_account
       , has_online_payment
       , has_stamps
       , has_pos
       , is_talent
       , has_featured_product
       , has_discount
       , last_order_date
       , first_order_date
       , restaurant_street
       , restaurant_door_number
       , restaurant_phone
       , restaurant_owner_contact_name
       , restaurant_owner_contact_last_name
       , left(restaurant_owner_contact_phones,200)
       , reception_system_name
       , delivery_time
       , min_shipping_amount
       , max_shipping_amount
       , min_delivery_amount
       , max_delivery_amount
       , qty_zones
       , publicity_cost
       , automation_cost
       , avg_rating
       , main_cousine
       , left(link,200)
       , left(logo,200)
       , is_debtor
       , contract_number
       , previous_state_id
       , change_state_date_id
       , avg_speed as avg_rating_speed
       , qty_current_gold_vip
       , qty_current_featured_product
       , is_logistic
       , left(account_owner,250)
       , is_day
       , is_night
       , address_id
       , is_premium
       , left(disabled_reason,1000)
	   , avg_total_amount_last_3_month
	   , avg_qty_order_last_3_month
	   , reception_system_enabled
		, has_mov
		, is_express
		 , main_cousine_category_id
FROM public.dim_restaurant
)