SELECT
  company_addresses.uuid,
  company_addresses.id,
  company_addresses.rdbms_id,
  company_addresses.company_uuid AS cp_company_uuid,
  company_addresses.company_id AS cp_company_id,
  addresses.user_uuid AS cp_user_uuid,
  addresses.user_id AS cp_user_id,

  addresses.address,
  addresses.address_other,
  addresses.building,
  addresses.campus,
  addresses.delivery_instructions,
  addresses.city AS city_name,
  addresses.district,
  addresses.entrance,
  addresses.floor,
  addresses.latitude,
  addresses.longitude,
  addresses.post_code,
  addresses.room,
  addresses.structure,
  addresses.type,
  company_addresses.state,
  company_addresses.is_state_active,
  company_addresses.is_state_deleted,
  company_addresses.is_state_suspended,
  addresses.is_flexible_address,
  company_addresses.created_at_utc,
  company_addresses.updated_at_utc,
  company_addresses.dwh_last_modified_utc,
FROM `{project_id}.pandata_intermediate.cp_company_locations` AS company_addresses
LEFT JOIN `{project_id}.pandata_intermediate.cp_addresses` AS addresses
       ON company_addresses.uuid = addresses.uuid
