apiVersion: batch/v1
kind: Job
metadata:
  name: debian
spec:
  template:
    spec:
      containers:
        - name: debian
          image: debian
          stdin: true
          tty: true
          command: ["cat"]
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 128Mi
      restartPolicy: Never
      nodeSelector:
        group: main
  backoffLimit: 4
