SELECT
  payments_quest_rules.uuid,
  payments_quest_rules.id,
  countries.rdbms_id,
  payments_quest_rules.country_code,
  payments_quest_rules.created_by_email,
  payments_quest_rules.status,
  payments_quest_rules.type,
  payments_quest_rules.sub_type,
  payments_quest_rules.name,
  payments_quest_rules.duration_iso8601,
  payments_quest_rules.is_active,
  payments_quest_rules.is_pay_below_threshold,
  payments_quest_rules.is_negative,
  payments_quest_rules.minimum_acceptance_rate,
  payments_quest_rules.no_show_limit,
  payments_quest_rules.start_time,
  payments_quest_rules.end_time,
  payments_quest_rules.start_at_utc,
  payments_quest_rules.end_at_utc,
  payments_quest_rules.created_at_utc,
  payments_quest_rules.updated_at_utc,
  payments_quest_rules.created_date_utc,
  payments_quest_rules.applies_to,
FROM `{project_id}.pandata_intermediate.lg_payments_quest_rules` AS payments_quest_rules
LEFT JOIN `{project_id}.pandata_intermediate.pd_countries` AS countries
       ON payments_quest_rules.country_code = countries.lg_country_code
