SELECT
  rider_referral_payments.uuid,
  rider_referral_payments.id,
  countries.rdbms_id,
  rider_referral_payments.lg_rider_uuid,
  rider_referral_payments.lg_rider_id,
  rider_referral_payments.lg_city_uuid,
  rider_referral_payments.lg_city_id,
  rider_referral_payments.lg_contract_uuid,
  rider_referral_payments.lg_contract_id,
  rider_referral_payments.referrer_lg_rider_uuid,
  rider_referral_payments.referrer_lg_rider_id,
  rider_referral_payments.referee_lg_rider_uuid,
  rider_referral_payments.referee_lg_rider_id,
  rider_referral_payments.lg_payment_cycle_uuid,
  rider_referral_payments.lg_payment_cycle_id,
  rider_referral_payments.region,
  rider_referral_payments.country_code,
  rider_referral_payments.city_name,
  rider_referral_payments.rider_name,
  rider_referral_payments.contract_type,
  rider_referral_payments.vehicle_type,
  rider_referral_payments.status,
  rider_referral_payments.paid_local,
  rider_referral_payments.payment_type_unit_amount,
  rider_referral_payments.timezone,
  rider_referral_payments.payment_cycle_start_at_utc,
  rider_referral_payments.payment_cycle_end_at_utc,
  rider_referral_payments.paid_period_start_at_utc,
  rider_referral_payments.paid_period_end_at_utc,
  rider_referral_payments.created_at_utc,
  rider_referral_payments.created_date_utc,
FROM `{project_id}.pandata_intermediate.lg_rider_referral_payments` AS rider_referral_payments
LEFT JOIN `{project_id}.pandata_intermediate.pd_countries` AS countries
       ON rider_referral_payments.country_code = countries.lg_country_code
