slack:
  channel: '#mkt-airflow-prod'
  channel_errors: '#mkt-airflow-prod'
  has_mentions: true

gcs_production: &gcs_production
  bucket_name: 'fulfilment-dwh-production-import'

bigquery:
  <<: *gcs_production
  project_id: 'fulfillment-dwh-production'
  create_views: true

dwh_merge_layer_databases:
  dwh_il:
    tables:
      - name: dim_countries
        s3:
          bucket: mkt-export-to-bq
  dwh_bl:
    tables:
      - name: marketing_orders
        s3:
          bucket: mkt-export-to-bq
