name: push and PR
on:
  push:
    branches:
      - stg
    # tags:        
    #   - stg

jobs:
  python_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/python_lint
      with:
        python-root-list: "./stg/airflow/dags/"
        use-pylint: false
        use-pycodestyle: false
        use-flake8: true
        use-black: false
        use-mypy: false
        use-isort: false
        extra-pylint-options: ""
        extra-pycodestyle-options: ""
        extra-flake8-options: ""
        extra-black-options: ""
        extra-mypy-options: ""
        extra-isort-options: ""

  dagValidation:
    needs: python_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Validate DAGs'
        uses: ./.github/actions/dag_validation
        with:
          requirementsFile: pro/airflow/requirements.txt
          dagPaths: pro/airflow/dags

  createPullRequest:
    needs: python_lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update Airflow Dags Automated
          committer: PedidosYa <noreply@pedidosya.com>
          author: ${{ github.actor }} <${{ github.actor }}@pedidosya.com>
          signoff: false
          branch: master
          delete-branch: false
          title: '[DTDO] Airflow Dags Automated to STG'
          body: |
            Update report
            - Updated dags with *today's* date
            - Auto-generated by Pull Request by DataOps 

          labels: |
            airflow dags
            automated pr
            stg
          assignees: dgarcia-peya
          # reviewers: estefano-ramirez
          # team-reviewers: |
          #   dataops
          draft: false


      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

          