name: Testing Airflow workflow
on:
  push:
    branches:
      - airflow

jobs:
  python_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@v1.3.0
      with:
        python-root-list: "./airflow/dags/"
        use-pylint: false
        use-pycodestyle: false
        use-flake8: true
        use-black: false
        use-mypy: false
        use-isort: false
        extra-pylint-options: ""
        extra-pycodestyle-options: ""
        extra-flake8-options: ""
        extra-black-options: ""
        extra-mypy-options: ""
        extra-isort-options: ""

  dagValidation:
    needs: python_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Validate DAGs'
        uses: ./.github/actions/dag_validation
        with:
          requirementsFile: airflow/requirements.txt
          dagPaths: airflow/dags

  createPullRequest:
    needs: dagValidation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: PedidosYa <noreply@pedidosya.com>
          author: ${{ github.actor }} <${{ github.actor }}@pedidosya.com>
          signoff: false
          branch: master
          delete-branch: false
          title: '[DTDO] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

          labels: |
            report
            automated pr
          assignees: dgarcia-peya
          # reviewers: estefano-ramirez
          # team-reviewers: |
          #   dataops
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
